CREATE TABLE S(
	S# CHAR(8) CONSTRAINT PK_S# PRIMARY KEY,
	sname VARCHAR2(20),
	status INT,
	city VARCHAR2(20)
);
CREATE TABLE P(
	P# CHAR(8) CONSTRAINT PK_P# PRIMARY KEY,
	pname VARCHAR2(20),
	color VARCHAR2(10),
	weight float,
	city VARCHAR2(20)
);
CREATE TABLE J(
	J# CHAR(8) CONSTRAINT PK_J# PRIMARY KEY,
	jname VARCHAR2(20),
	city VARCHAR2(20)
);
CREATE TABLE SPJ(
	S# CHAR(8),
	P# CHAR(8),
	J# CHAR(8),
	QTY INT,
	CONSTRAINT    FK_S#  FOREIGN KEY (S#) REFERENCES S(S#),
	CONSTRAINT    FK_P#  FOREIGN KEY (P#) REFERENCES P(P#),
	CONSTRAINT    PK_J#  FOREIGN KEY (J#) REFERENCES J(J#)
);